# Example Configuration for API Gateway

# Define services with their respective configurations
[services]

[services.notification_service]
url = "https://google.com"

# Define routing configurations
[[routes]]
path = "/notify"
service = "notification_service"

[[routes]]
path = "/user"
service = "user_service"